import { createConstants } from '../utils';

export default createConstants(
  'LOGIN_USER_REQUEST',
  'LOGIN_USER_FAILURE',
  'LOGIN_USER_SUCCESS',
  'LOGOUT_USER',
  'RECEIVE_PROTECTED_DATA',
  'GET_USER_INFO_REQUEST',
  'GET_USER_INFO_SUCCESS',
  'GET_USER_INFO_FAILURE',
  'GET_USERS_REQUEST',
  'GET_USERS_FAILURE',
  'GET_USERS_SUCCESS',
);
